### ISSUE TITLE
Natural spawn option

### ISSUE THREAD

**Issue by Jukabofy** [Lykrast/MeetYourFight#11]
I would like to have the option to spawn them in a specifical biome, even custom ones, for example, with the swampjaw, with low spawnrate in soul sand valley.
For hardcore modpacks and some specifical events
If not, is there an external tool(mod) or something that could help me?

**Comment by Lykrast** [comment]
I feel like having those spawn naturally would be miserable, cause they're designed to take all your intentions into the fight, so imo it has to be opt in (via the dedicated spawn item). So it's not planned in the mod itseld.

I think [In Control!](https://www.curseforge.com/minecraft/mc-mods/in-control) should do the job if you really want it. Not sure how/if it works though. Maybe KubeJS can also adjust spawn? I'm not sure on that one.
