### ISSUE TITLE
World dead-lock when using Depth Star Ability

### ISSUE THREAD

**Issue by InteJason** [Lykrast/MeetYourFight#13]
Version: 1.18.2 - 1.2.4

https://paste.ee/p/BxJiM

**Comment by Lykrast** [comment]
Well I can't seem to reproduce it like that. I'll need more info:

* Forge version
* What other mods are in your instance
* Where you near some worldgen structure when it crashed/locked? Could you try on a fresh world right at spawn just to double check?
