### ISSUE TITLE
Minecraft not loading

### ISSUE THREAD

**Issue by MrCoolz123456** [Lykrast/MeetYourFight#14]
I was playing Minecraft with this mod and the Guns Without Roses mod. When Minecraft opened it immediately crashed. I tried again but it did not work. Here is the crash file
[crash-2022-06-19_16.01.56-client.txt](https://github.com/Lykrast/MeetYourFight/files/8934966/crash-2022-06-19_16.01.56-client.txt)
I don't really understand these things. I am using 1.19 on all mods.

**Comment by Lykrast** [comment]
That is a weird error, nothing from this mod seems to pop up in the log. In fact, no mod even appears in this crashlog. You seem to be on Forge 41.0.38 which is the latest, so probably not that.

Can you show your complete mod list? And also can you try starting it without Meet Your Fight and Guns Without Roses to see if that changes anything?

If it still crashes without those mods, then at least we know it's not them, so you can always try removing all the mods and adding them back little by little until it crashes again.
