### ISSUE TITLE
 [1.19] Forge breaking changes

### ISSUE THREAD

**Issue by Baggytrousers27** [Lykrast/MeetYourFight#15]
Forges 41.0.64+ and 41.0.94+ introduce breaking changes for meetyourfight-1.19-1.2.5.

**Comment by Lykrast** [comment]
I'm fully aware of this, but I'm not planning to port them until 1.19.1 comes along because I don't have time at the moment.

I might do it before if I get some time, but 0 guarantee here.

**Comment by Baggytrousers27** [comment]
Completely understandable.
