### ISSUE TITLE
World dead hang when the depth star is used (1.18.2)

### ISSUE THREAD

**Issue by InteJason** [Lykrast/MeetYourFight#22]
This happens with the epic fight mod. The log doesn't seem to show anything useful: https://mclo.gs/QvBf5lI
Forge Version: 40.2.14

To replicate:
1) Have both epic fight and meet your fight installed.
2) Right click using depth star.

**Comment by SettingDust** [comment]
https://mclo.gs/LeJdgwr and it's 1.18.2

**Comment by SettingDust** [comment]
The https://github.com/Lykrast/MeetYourFight/blob/master/src/main/java/lykrast/meetyourfight/item/DepthStar.java#L35 timeleft is 2147483644

**Comment by SettingDust** [comment]
https://github.com/Yesssssman/epicfightmod/blob/1.18.2/src/main/java/yesman/epicfight/events/PlayerEvents.java#L90
