### ISSUE TITLE
Swamp Jaw Dropping Bomb Causes Game to Crash

### ISSUE THREAD

**Issue by LThreeZeroT** [Lykrast/MeetYourFight#23]
I was playing Dawncraft, and I summoned the Swamp Jaw boss. Every time it would attack, via dropping bombs, my game crashes instantly. I tried restarting my computer, removing all of my own added mods (there were only 2), and even increasing my RAM, but absolutely nothing worked.

**Comment by Lykrast** [comment]
Can't do anything without the logs.

**Comment by haribbo77** [comment]
same issue here
[crash-2024-06-03_22.36.41-server.txt](https://github.com/user-attachments/files/15540569/crash-2024-06-03_22.36.41-server.txt)

**Comment by LThreeZeroT** [comment]
My crash reports probably won't help, but okay.

https://mclo.gs/dPBIRpr

**Comment by Lykrast** [comment]
DawnCraft Tweaks seems like the primary culprit.

Don't have time to test anything right now, but like if any of you could test in a world without that mod maybe that could help.

**Comment by LThreeZeroT** [comment]
Ok.

**Comment by LThreeZeroT** [comment]
I actually don't think it's possible to play without Dawncraft tweaks. I'll try though.

**Comment by LThreeZeroT** [comment]
The developers of the modpack fixed the bug. The game no longer crashes.
