### ISSUE TITLE
Jagershot does not work?

### ISSUE THREAD

**Issue by DatenThielt** [Lykrast/MeetYourFight#5]
Instructions unclear, states it shoots projectiles but does not say what kind? did not seem to work with arrows!

Thanks!

**Comment by Lykrast** [comment]
If you're seeing it (and the Phantasmal Rifle) in game that means you have Guns Without Roses installed. These 2 are guns that behave like those from that mod, and so they use Guns Without Roses bullets (Flint Bullet, Iron Bullet, Blaze Bullet, or Maws of Gluttony).
